### ISSUE TITLE
FR: power supply and fan status for switch stacks and virtual chassis

### ISSUE THREAD

**Issue by noziwatele** [netdisco/netdisco#1017]
Hi all,

Firstly, many thanks for your hard work in bringing Netdisco to us. We use it quite a bit in our organisation and we love it.

One issue we have encountered is that we have many Cisco switch stacks (C3850s and C9300s mostly), and also quite a few VSS/SVL virtual chassis (C6840s and C9500s), and for these systems the power supply and fan status does not register on the Device Details page. It would be great if the PSU and fan status could be grabbed for each switch in the stack and be made available for display and reports.

## Requested Behavior

Perhaps something similar to the PoE Status section of Device Details, with a list of switch modules and their corresponding PS and fan status?

|  |  |
| --- | --- |
| Hardware Status | Module 1: PS1 [ps-model]: ok, PS2 [ps-model]: ok, Fan: ok |
|                             | Module 2: PS1 [ps-model]: ok, PS2 [ps-model]: ok, Fan: ok |
|                             | Module 2: PS1 [ps-model]: ok, PS2 [ps-model]: ok, Fan: ok |

## Current Behavior

This is what we see on the Device Details page for the models of switch stack and virtual chassis listed above:

|  |  |
| --- | --- |
| Hardware Status | Fan: |
|                             | PS1 []: |
|                             | PS2 []: |

## Environment

App::Netdisco: 2.61.0
SNMP::Info: 3.92
DB Schema: 78
PostgreSQL: 13.00.4
Perl: 5.36.0

Please let me know if you need any more info. Cheers

**Comment by rc9000** [comment]
I had a quick look at this, unfortunately it's not something that can be easily fixed in five minutes.

On the snmp-info side, it looks like the support for [CISCO-ENVMON-MIB](http://www.circitor.fr/Mibs/Html/C/CISCO-ENVMON-MIB.php) is not very consistently implemented. [C4000.pm](https://github.com/netdisco/snmp-info/blob/master/lib/SNMP/Info/Layer3/C4000.pm#L54) does almost the right thing, but it would need to be applied to a lot more models. This should probably be a CiscoEnvmon top-level module similar to `lib/SNMP/Info/CiscoQOS.pm` and only from there included in the right layers and product families. Also, it only queries ps1_/ps_2 but in a stack there can be of course a lot more.

This problem also extends into Netdisco, `device` has fields for ps1, ps2 and fan - but from these stacks the walk looks like e.g.

    Cat9300FixedSwitchStack fans
    .1.3.6.1.4.1.9.9.13.1.4.1.2.1017 = STRING: Switch 1 - FAN - T1 1, Normal
    .1.3.6.1.4.1.9.9.13.1.4.1.2.1018 = STRING: Switch 1 - FAN - T1 2, Normal
    .1.3.6.1.4.1.9.9.13.1.4.1.2.1019 = STRING: Switch 1 - FAN - T1 3, Normal
    .1.3.6.1.4.1.9.9.13.1.4.1.2.2017 = STRING: Switch 2 - FAN - T1 1, Normal
    .1.3.6.1.4.1.9.9.13.1.4.1.2.2018 = STRING: Switch 2 - FAN - T1 2, Normal
    .1.3.6.1.4.1.9.9.13.1.4.1.2.2019 = STRING: Switch 2 - FAN - T1 3, Normal
    .1.3.6.1.4.1.9.9.13.1.4.1.2.3017 = STRING: Switch 3 - FAN - T1 1, Normal
    .1.3.6.1.4.1.9.9.13.1.4.1.2.3018 = STRING: Switch 3 - FAN - T1 2, Normal
    .1.3.6.1.4.1.9.9.13.1.4.1.2.3019 = STRING: Switch 3 - FAN - T1 3, Normal
    .1.3.6.1.4.1.9.9.13.1.4.1.3.1017 = INTEGER: normal(1)
    .1.3.6.1.4.1.9.9.13.1.4.1.3.1018 = INTEGER: normal(1)
    .1.3.6.1.4.1.9.9.13.1.4.1.3.1019 = INTEGER: normal(1)
    .1.3.6.1.4.1.9.9.13.1.4.1.3.2017 = INTEGER: normal(1)
    .1.3.6.1.4.1.9.9.13.1.4.1.3.2018 = INTEGER: normal(1)
    .1.3.6.1.4.1.9.9.13.1.4.1.3.2019 = INTEGER: normal(1)
    .1.3.6.1.4.1.9.9.13.1.4.1.3.3017 = INTEGER: normal(1)
    .1.3.6.1.4.1.9.9.13.1.4.1.3.3018 = INTEGER: normal(1)
    .1.3.6.1.4.1.9.9.13.1.4.1.3.3019 = INTEGER: normal(1)
    
    
    C9606RVirtualStack psu
    .1.3.6.1.4.1.9.9.13.1.5.1.2.19 = STRING: Switch 1 Power Supply Module 1
    .1.3.6.1.4.1.9.9.13.1.5.1.2.20 = STRING: Switch 1 Power Supply 1
    .1.3.6.1.4.1.9.9.13.1.5.1.2.23 = STRING: Switch 1 Power Supply Module 2
    .1.3.6.1.4.1.9.9.13.1.5.1.2.24 = STRING: Switch 1 Power Supply 2
    .1.3.6.1.4.1.9.9.13.1.5.1.2.517 = STRING: Switch 2 Power Supply Module 1
    .1.3.6.1.4.1.9.9.13.1.5.1.2.518 = STRING: Switch 2 Power Supply 1
    .1.3.6.1.4.1.9.9.13.1.5.1.2.521 = STRING: Switch 2 Power Supply Module 2
    .1.3.6.1.4.1.9.9.13.1.5.1.2.522 = STRING: Switch 2 Power Supply 2
    .1.3.6.1.4.1.9.9.13.1.5.1.3.19 = INTEGER: normal(1)
    .1.3.6.1.4.1.9.9.13.1.5.1.3.20 = INTEGER: normal(1)
    .1.3.6.1.4.1.9.9.13.1.5.1.3.23 = INTEGER: normal(1)
    .1.3.6.1.4.1.9.9.13.1.5.1.3.24 = INTEGER: normal(1)
    .1.3.6.1.4.1.9.9.13.1.5.1.3.517 = INTEGER: normal(1)
    .1.3.6.1.4.1.9.9.13.1.5.1.3.518 = INTEGER: normal(1)
    .1.3.6.1.4.1.9.9.13.1.5.1.3.521 = INTEGER: normal(1)
    .1.3.6.1.4.1.9.9.13.1.5.1.3.522 = INTEGER: normal(1)

So presumable we'd also need a schema extension to store this properly? I could see adding a device_sensor structure similar to device_module, since there would be some other things in these mibs that are also interesting and I'm pretty sure other vendors have similar proprietary MIB subtrees. Here's another example from a  38xxstack with also some temperature sensors in the mix: 

    .1.3.6.1.4.1.9.9.13.1.3.1.2.1012 = STRING: Switch 1 - Inlet Temp Sensor, GREEN
    .1.3.6.1.4.1.9.9.13.1.3.1.2.2012 = STRING: Switch 2 - Inlet Temp Sensor, GREEN
    .1.3.6.1.4.1.9.9.13.1.3.1.3.1012 = Gauge32: 31 degrees Celsius
    .1.3.6.1.4.1.9.9.13.1.3.1.3.2012 = Gauge32: 30 degrees Celsius
    .1.3.6.1.4.1.9.9.13.1.3.1.4.1012 = INTEGER: 56 degrees Celsius
    .1.3.6.1.4.1.9.9.13.1.3.1.4.2012 = INTEGER: 56 degrees Celsius
    .1.3.6.1.4.1.9.9.13.1.3.1.5.1012 = INTEGER: 0 degrees Celsius
    .1.3.6.1.4.1.9.9.13.1.3.1.5.2012 = INTEGER: 0 degrees Celsius
    .1.3.6.1.4.1.9.9.13.1.3.1.6.1012 = INTEGER: normal(1)
    .1.3.6.1.4.1.9.9.13.1.3.1.6.2012 = INTEGER: normal(1)
    .1.3.6.1.4.1.9.9.13.1.3.1.7.1012 = INTEGER: 31
    .1.3.6.1.4.1.9.9.13.1.3.1.7.2012 = INTEGER: 30
    .1.3.6.1.4.1.9.9.13.1.4.1.2.1017 = STRING: Switch 1 - FAN - T1 1, Normal
    .1.3.6.1.4.1.9.9.13.1.4.1.2.2017 = STRING: Switch 2 - FAN - T1 1, Normal
    .1.3.6.1.4.1.9.9.13.1.4.1.3.1017 = INTEGER: normal(1)
    .1.3.6.1.4.1.9.9.13.1.4.1.3.2017 = INTEGER: normal(1)
    .1.3.6.1.4.1.9.9.13.1.5.1.2.1015 = STRING: Switch 1 - Power Supply A, Normal
    .1.3.6.1.4.1.9.9.13.1.5.1.2.2015 = STRING: Switch 2 - Power Supply A, Normal
    .1.3.6.1.4.1.9.9.13.1.5.1.3.1015 = INTEGER: normal(1)
    .1.3.6.1.4.1.9.9.13.1.5.1.3.2015 = INTEGER: normal(1)

What we generally do is poll Envmon values in our more active monitoring tools (Prometheus, OpenNMS, Icinga and whathaveyou) that will also send an alert when something goes out of range, but I still see how it could be worthwhile to have this stuff work properly in Netdisco for stacks also.

**Comment by ollyg** [comment]
closing and moving to wishlist
