### ISSUE TITLE
Delete devices and force discovery via API

### ISSUE THREAD

**Issue by mmarin11** [netdisco/netdisco#1030]
Dear netdisco community

Is there a way to force discovery and delete devices via the API? We are trying to integrate netdisco with netbox and the idea would be to trigger discovery and deletion via netbox webhooks.

Regards

**Comment by ollyg** [comment]
Hi @mmarin11 
This is actually work in progress right now, we have this issue for the feature request: #1015 
So, I hope it will be released in a few days or a week.

I'd be interested to know your integration approach, as I'm a netbox user as well.
Also what you mean by "force" ... is that because timeouts stop it being discovered like in the other ticket?

Anyway, if OK, I will close this ticket and you can comment on and follow the other one?

Many thanks!

**Comment by ollyg** [comment]
force discovery is implemented - there are now API endpoints to manage the queue, and if you submit a job via the API it will always be run (ignores skiplist) or you can delete jobs for a device which deletes the skiplist and gives you a blank slate.

reopening this for the delete device API feature

**Comment by ollyg** [comment]
Ahh @mmarin11 I realised that delete device is already implemented, because it's a backend job! You need to queue the job `delete` and if you want the nodes to be preserved, add a `true` value on the `port` parameter (mnemonic: preserve).

I'll add this to API docs.
