### ISSUE TITLE
Netdisco 2 Training

### ISSUE THREAD

**Issue by leaoereno** [netdisco/netdisco#1115]
I would like to suggest that training be developed for administrator users of the tool.
With topics such as standalone installation, distributed among other topics that are comprehensive to the people who administer the tool.

**Comment by rc9000** [comment]
The best thing we currently have is the [wiki](https://github.com/netdisco/netdisco/wiki), did you check that out already or do you have topics that you think are missing and we should expand on?

I generally like the idea of a Netdisco training, but our company has developed some in-person and self-guided courses for other open source tools and the effort to get the first class off the ground is enormous. I suspect that for a somewhat niche software like Netdisco, it might just not be viable. 

For help in specifc topics, the IRC is also a great resource: [irc.libera.chat#netdisco](https://kiwiirc.com/nextclient/irc.libera.chat/netdisco)

**Comment by leaoereno** [comment]
Hello Chris, how are you, greetings from Brazil.

In fact, I miss a more administrative guide, as the installation and configuration part is very intuitive...
Perhaps in the web interface I can indicate which server is performing the discovery for that particular device, or, when I am performing the discovery through the web interface, I can choose which server will do it.
Another thing I also miss is being able to indicate a file, be it txt or json to discover different IPs using the netdisco-do command.

Regarding the chat, the many times I logged in, at different times, I didn't find anyone connected.

Another suggestion is to set up a topology on the wiki itself, showing what standalone installations are like (Web, Backend and database) and a distributed one, with a component on each server.

Anyway, thank you for your attention and I would like to congratulate you on the tool and in whatever way I can help or contribute to growth, count on me.

Regards

De: Christian Ramseyer ***@***.***>
Enviada em: sexta-feira, 3 de novembro de 2023 18:22
Para: netdisco/netdisco ***@***.***>
Cc: leaoereno ***@***.***>; Author ***@***.***>
Assunto: Re: [netdisco/netdisco] Netdisco 2 Training (Issue #1115)


The best thing we currently have is the wiki<https://github.com/netdisco/netdisco/wiki>, did you check that out already or do you have topics that you think are missing and we should expand on?

I generally like the idea of a Netdisco training, but our company has developed some in-person and self-guided courses for other open source tools and the effort to get the first class off the ground is enormous. I suspect that for a somewhat niche software like Netdisco, it might just not be viable.

For help in specifc topics, the IRC is also a great resource: irc.libera.chat#netdisco<https://kiwiirc.com/nextclient/irc.libera.chat/netdisco>

**Comment by rc9000** [comment]
> Perhaps in the web interface I can indicate which server is performing the discovery for that particular device, or, when I am performing the discovery through the web interface, I can choose which server will do it.

Choosing is maybe difficult since this has to match up with the constraints (`devices_only` and similar) in the config. But showing which one did it last should not be hard since we can look it up in the job queue. Maybe submit this as a separate feature request/wishlist issue here?

> Another thing I also miss is being able to indicate a file, be it txt or json to discover different IPs using the netdisco-do command.

 * You can give it an ip range, e.g. `netdisco-do discover --enqueue -d 192.168.7.0/24`
 * Or use this bash loop if you have a file with hostnames or ip addresses, one per line: `for x in $(<fortigates.txt) ; do netdisco-do arpnip -D -d  ; done`

> Regarding the chat, the many times I logged in, at different times, I didn't find anyone connected.

Yes it's a very slow channel, you sometimes have to stick around for a couple of hours. Using a client that can stay permanently connected like https://www.irccloud.com/ or running irssi in tmux/screen is highly recommended. And if it still doesn't work out, just repost the question here as an issue.

> Another suggestion is to set up a topology on the wiki itself, showing what standalone installations are like (Web, Backend and database) and a distributed one, with a component on each server. Anyway ... in whatever way I can help or contribute to growth, count on me.

Sure if you have a draft for a page like this in the wiki, go ahead and make a first version and then we can fill in missing or unclear bits. I'm not quite sure how the github wiki works, but I think you can make/edit pages and then either submit them as a pull request or maybe even just update it directly.

Valeu!
