### ISSUE TITLE
IPv4/IPv6 dual stack host renumber

### ISSUE THREAD

**Issue by glaskoncilla** [netdisco/netdisco#1123]
Software	Version
App::Netdisco	2.52.1
SNMP::Info	3.81
DB Schema	70
PostgreSQL	13.00.7
Perl	5.32.1

Hi,

seems like Netdisco has some problems with renumbering dual stack devices where we want to change IPv6 address to IPv4 address on the same interface.
Our default configuration is we force interface Loopback0 as device_intentitity;

device_identity:
          'any': 'port:(?i)loopback0' 

And this works as expected where IP address on loopback0 is IPv4 only.
Problem is on devices where loopback0 is IPv4/IPv6 dual stacked and Netdisco choose IPv6 address as device_identity.
Tipically, with IPv4 only host, netdisco-do renumber would solve the problem, I've tried that but device returns to IPv6 as device_identity.

So I've tried with something similar to;

host_groups:
          dualstack_routers:
             - !!perl/regexp ^_hostnameregexp_*$

device_identity:
          'group:dualstack_routers':
             - '10.10.10.0/24'
             - 'port:(?i)loopback0'
          'any': 'port:(?i)loopback0'

but devices keep return with IPv6 address as identity, no matter if I re-discover the device or completely delete devices and discover it again.

Problem is not with Netdisco as such because Netdisco is also dual stacked but we use Netdisco as source of truth for other IPv4 only applications so IPv6 address as device mgmt IP becomes problematic.

Is this a bug or am I missing something in configuration?

**Comment by ollyg** [comment]
Hi @glaskoncilla thanks for the question, I think there are a few different things going on here and you should be able to fix it in config.

Simplest option might be to go with your original "any" approach but exclude all IPv6 or equally restrict to only IPv4, like so:

```
device_identity:
  'group:__ANY__':
    'op:and'
    '!::/0'
    'port:(?i)loopback0'

# or

device_identity:
  'group:__ANY__':
    'op:and'
    '0.0.0.0/0'
    'port:(?i)loopback0'
```

Note the use of "op:and" because you want to require both to be true.

Your `dualstack_routers` approach should work but you'll need to adjust `device_identity` to be an ordered list instead of a dictionary, so that Netdisco encounters that rule before the "any" rule, and also add the "op:and" rule again.

At the end of the documentation there is an example of using a list: https://github.com/netdisco/netdisco/wiki/Configuration#device_identity

Hope that helps and do let me know how it goes!

By the way, if you have other web tools using same IPs as Netdisco you might be interested in the new `external_links` feature: https://github.com/netdisco/netdisco/wiki/Configuration#external_links

regards
Oliver.

**Comment by glaskoncilla** [comment]
Hi Oliver,

excluding IPv6 addresses as device identity helped, thank you very much!

External links, great feature, till now I've done some dirty hacking of Netdisco code for this purpose.
