### ISSUE TITLE
discoverall not re-discovering some already known devices

### ISSUE THREAD

**Issue by alkalinelito** [netdisco/netdisco#1211]
## Expected Behavior

discoverall should re-discover -all- already known devices

## Current Behavior
discoverall not re-discoverying -some- already known devices
I have around 500 added devices (all cisco same config all) , and around 8-12 are not being discovered when discoverall is run.
This happens in the daily discvoeryall or if I manually run it.
If I manually run discover on those devices it works ok. 
This behavior is random , they are not always the same devices.
I found out about this when some devices where being marked "down" in makerancidconfig.

## Possible Solution
discoverall  -D doesnt really show much info, so I'm asking how should I debug this.

## Your Environment
Netdisco installed on debian bookworm
App::Netdisco	2.76.0
SNMP::Info	3.970001
DB Schema	87
PostgreSQL	15.00.6
Perl	5.36.0

**Comment by inphobia** [comment]
i'd guess https://github.com/netdisco/netdisco/wiki/Troubleshooting#change-the-snmp-community-string-for-a-device

that or perhaps the devices have multiple ip's (vrf's for example).

https://github.com/netdisco/netdisco/wiki/Configuration#snmp_field_protection is also something to look at.

`-DIS` as debugging option for netdisco-do might be a better choice to debug, feel free to contact us via private mail or irc.

**Comment by ednpnoble** [comment]
I am seeing a similar behavior.  The same 4 devices regularly discover during the discoverall process (Scheduled or manual), the other devices don't try to discover.

I don't think it is the SNMP string because ARPNIP continues to run on schedule

Sample device where problem occurs
```
Today's date      2024-08-06
First Discovered  2024-06-27 15:44
Latest Discover   2024-07-16 07:05
Latest Arpnip     2024-08-06 12:10
Latest Macsuck    2024-07-30 10:43
```

like the OP, I can Manually discover the individual device and it discovers just fine.

if I do a discoverall with -DIS flag only 4 of the 21 devices queue up for discovery.  It's not that they are failing, it never attempts the discover.

```
netdisco@[hostname]:~$ ./bin/netdisco-do -DIS discoverall
[546367] 2024-08-08 22:17:16  info App::Netdisco version 2.076005 loaded.
[546367] 2024-08-08 22:17:16  info discoverall:  started at Thu Aug  8 15:17:16 2024
[546367] 2024-08-08 22:17:16 debug discoverall: running with timeout 600s
[546367] 2024-08-08 22:17:16 debug //// CHECK \\\\ phase
[546367] 2024-08-08 22:17:16 debug â® worker Internal::BackendFQDN p1000000
[546367] 2024-08-08 22:17:16  info resolving backend hostname...
[546367] 2024-08-08 22:17:16 debug Backend identity set to [hostname]
[546367] 2024-08-08 22:17:16 debug â® worker Internal::SNMPFastDiscover p1000000
[546367] 2024-08-08 22:17:16 debug running with configured SNMP timeouts
[546367] 2024-08-08 22:17:16 debug â® worker DiscoverAll p0
[546367] 2024-08-08 22:17:17 debug â¬
 (done) Discoverall is able to run
[546367] 2024-08-08 22:17:17 debug //// MAIN \\\\ phase
[546367] 2024-08-08 22:17:17 debug â® worker DiscoverAll p0
[546367] 2024-08-08 22:17:17 debug â¬
 (done) Queued discover job for all devices
[546367] 2024-08-08 22:17:17  info discoverall: finished at Thu Aug  8 15:17:17 2024
[546367] 2024-08-08 22:17:17  info discoverall: status done: Queued discover job for all devices
```

```
Software       Version
App::Netdisco  2.76.5
SNMP::Info     3.970.1
DB Schema      87
PostgreSQL     12.00.18
Perl           5.30.0
```


Queuing up a primeskiplist does not appear to help either.

**Comment by ednpnoble** [comment]
Scratch my last.  

I think I discovered the root cause of the issue, but may be OPs root cause too.

Each one of my devices had hit 16 Failed SNMP Connections during a network reconfiguration.  Going into the `SNMP Connect Failures` menu and hitting the "Try Again" button resolves it for individual devices for me.

Is there a way to clean this list via netdisco-do or better yet, a configuration option to have it purge this list periodically?

I see the snmpretries configuration option, but I don't think that is only relevant for any given attempt.

**Comment by rc9000** [comment]
Hi @ednpnoble, I think the [retry_after](https://github.com/netdisco/netdisco/wiki/Configuration#workers) in the `workers:` config should address that. There should also be a default of retrying after 7 days. Do you think the devices have been stuck undiscovered longer already?

**Comment by ednpnoble** [comment]
@rc9000 - My workers configuration is "unconfigured" so it should be defaulting to the internal defaults in config.yml (reference below), but I don't think this is happening.  
By my math, 22 days (2024-07-16 to 2024-08-06) had passed.  

According to documentation that you referenced, the default should be 7 days. 

Documentation reads as:
> retry_after is the time when each job is retried once, even when permanently deferred. The default is each job retried once per week. To disable this feature (that is, never periodically retry) configure the setting with a value of zero.

The hiccup here is these aren't worker jobs yet.  They don't get scheduled by discover-all at all.  So, I think this setting, as described, might not be the culprit either. 

I think it is breaking down where the discoverall job is choosing which jobs to schedule and just isn't scheduling these at all, for some reason.


Default Config reference for this setting
https://github.com/netdisco/netdisco/blob/dbe2d7e0e2d0b6aa22e80b9182c893ca01bd6438/share/config.yml#L598 

snippet from my deployment.yml
``` 
#workers:
#  tasks: 'AUTO * 2'
#
```

**Comment by ollyg** [comment]
It looks to me like the backend is functioning correctly...?

Note that if you manually run any single discover job, it is forced to run (ignores the deferrals) by design. Because you asked for it.

You can reset all the deferrals by restarting the backend (actually it sets the deferrals to "max_deferrals - 1").

Currently there's no way to reset completely the skipping, other than going into the database and emptying the device_skip table and then restart the backend (or run the primeskiplist job).

If you still believe the discoverall selection has a bug, you can run it at command line with -DQ to see the SQL and examine it to test.
