### ISSUE TITLE
error request to GET /ajax/content/report/moduleinventory crashed: core

### ISSUE THREAD

**Issue by netdisco-automation** [netdisco/netdisco#239]
Hi,

When I tried to export a report to csv for device/module inventory/Module class I get this error on the webpage with no csv file produced:

IE or Firefox produce the same result

        File not found

        Firefox can't find the file at                 
        https://netdisco2.consult.com/ajax/content/report/moduleinventory?
        device=&description=&name=&type=&model=&serial=&class=module.

        Check the file name for capitalization or other typing errors.
        Check to see if the file was moved, renamed or deleted.

When I look at the netdisco-web log I see this error every time I try to export that specific report:

[2017] 2015-05-27 19:36:20 error request to GET /ajax/content/report/moduleinventory crashed: core - template - undef error - Can't use string ("") as a SCALAR ref while "strict refs" in use at /data/netdisco/perl5/lib/perl5/Text/CSV_PP.pm line 267.
 at /data/netdisco/perl5/lib/perl5/Dancer/Template/Abstract.pm line 93.
[2019] 2015-05-27 19:40:12 error request to GET /ajax/content/report/moduleinventory crashed: core - template - undef error - Can't use string ("") as a SCALAR ref while "strict refs" in use at /data/netdisco/perl5/lib/perl5/Text/CSV_PP.pm line 267.
 at /data/netdisco/perl5/lib/perl5/Dancer/Template/Abstract.pm line 93.
[2017] 2015-05-27 19:42:39 error request to GET /ajax/content/report/moduleinventory crashed: core - template - undef error - Can't use string ("") as a SCALAR ref while "strict refs" in use at /data/netdisco/perl5/lib/perl5/Text/CSV_PP.pm line 267.
 at /data/netdisco/perl5/lib/perl5/Dancer/Template/Abstract.pm line 93.

I don't know if the number of record I have for this inventory is causing it to crash?
The list show 16,000+ for this specific inventory list.

I export other reports fine. It just this one that keep crashing.

Anyone else experienced this?

My system information:

Software 	Version
App::Netdisco 	2.032005
DB Schema 	v40
Dancer 	        1.3136
Bootstrap 	2.3.1
PostgreSQL 	PostgreSQL 8.4.20 on x86_64-redhat-linux-gnu, 
                compiled by GCC gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-9), 64-bit.
                 DBI 1.633, DBD::Pg 2.15.1
SNMP::Info 	3.27
Perl 	        5.010001

Reported by: jimlead

Original Ticket: [netdisco/netdisco2/235](https://sourceforge.net/p/netdisco/netdisco2/235)

**Comment by kadamski-york** [comment]
Same issue, but only 39 rows. To get around this I added "no strict 'refs';" just before line 267

**Comment by inphobia** [comment]
are you still running the same versions as listed in the original issue?

if i can deduce it correctly that's on red hat enterprise linux 6.6. i guess the first question is what version of text::csv are you running? it seems not to be the operating system provided one when looking at your error log (which might be a good thing, because rhel 6.6 shipped with a now 9  year old text::csv 1.16)

if at all possible i would advise to upgrade to something more recent first, or even better set up a new server.

make sure to follow:
https://metacpan.org/pod/App::Netdisco#Upgrading-from-2.x
https://github.com/netdisco/netdisco/wiki/Release-Notes

since a lot has changed between 2.032005 and now.
