### ISSUE TITLE
Travis CI

### ISSUE THREAD

**Issue by djzort** [netdisco/netdisco#291]
Oliver, could you please connect the netdisco group to travis-ci ?

Cheers

**Comment by ollyg** [comment]
I'm not sure what that really means, but I was a bit concerned at attempting to log in to the travis-ci.org site that it will gain access to my private email address listed in Github. So I declined.

Perhaps there's a way for me to enable the netdisco organisation without my own account; I will look into it.

**Comment by djzort** [comment]
bump my access in the group and i will hook it to mine

**Comment by ollyg** [comment]
So I logged into Travis CI as our netdisco automation user (@netdisco-automation) and it seemed to sync everything. I'm not sure what the next steps are, but can you take it from here?

I'm not comfortable at the moment either handing out full admin rights to the netdisco project account on github (because that allows all kinds of things such as unprotecting branches and messing with user rights), or letting Travis CI have such access to repos and email addresses. All seems a bit much to me! If these are necessary, I need to understand what the service brings us in return.

**Comment by djzort** [comment]
travis-ci will send emails when builds fail or succeed for the first time having been failing. so some email address must be disclosed to them.

**Comment by djzort** [comment]
ok i can see that netdisco now is in travis-ci, and travis has sync'd the 6 repos.

however, i dont have access to enable travis to start building any of them.

if you go to travis-co.org, click the "+" on the LHS next to "My Repositories".
then click "Netdisco project", then toggle on "netdisco/netdisco". 
as the .travis.yml file already exists, it should then build and succeed.

**Comment by fenner** [comment]
I toggled on netdisco/netdisco, but I think Travis needs a push to trigger
a build.

  Bill

**Comment by djzort** [comment]
pushed the build status ruby image on to the readme file, should do it 
See https://github.com/netdisco/netdisco/commit/bb44ed404664a32a0de5c1e11345c5d1c9f4c903

**Comment by djzort** [comment]
success.

**Comment by djzort** [comment]
ok all good. closing
