### ISSUE TITLE
Multiple LLDP management addresses

### ISSUE THREAD

**Issue by fabled** [netdisco/netdisco#310]
Cisco IOS announces both IPv4 and IPv6 management addresses in LLDP PDUs and also in the SNMP LLDP-MIB data. Currently, netdisco will stop auto discovery to such devices.

## Expected Behavior
Netdisco will handle properly multiple LLDP management addresses, and connect to at least one or all of them (in prioritized sequential order) to discover the neighbor.

## Current Behavior
Netdisco will "self circuit" the port and stop auto discovery.
See: https://github.com/netdisco/netdisco/blob/master/lib/App/Netdisco/Core/Discover.pm#L820

## Additional notes
It seems that when HP ProCurve devices are attached to Cisco devices announcing both IPv4 and IPv6 address, it will register and report only the IPv4 address in LLDP-MIB - Cisco IOS will report both addresses in LLDP-MIB.

For the above reasons, I would like to be able to configure the following logic for netdisco:
1. Prefer IPv6 for LLDP discovery when seen, fallback to IPv4
1. When discovering device, query the LLDP local management addresses table, and use IPv6 from there as the canonical device address

**Comment by ollyg** [comment]
This could be part of #36 which is a table to store LLDP capabilities. We can store the first/highest IP in the remote_ip port column for legacy apps, and then switch Netdisco2 to using the new LLDP capabilities table for its own work.

**Comment by ollyg** [comment]
Note: could add a flag to the device_ip table which is `is_management`, based on what the local management addresses table reports for that device.

**Comment by ollyg** [comment]
Fixed in 4ad94977.

**Comment by ollyg** [comment]
Must say that this seems to contradict the comments in SNMP::Info::LLDP and also #263.

Netdisco uses c_ip() which in turn will call lldp_ip(). According to the source lldp_ip() will return only IPv4 addresses as it filters for the correct protocol. lldp_addr() will return both v4/v6 but is not used by Netdisco, and lldp_ipv6() will return IPv6 but is also not used.

Happy for someone to enlighten me :confused:

**Comment by ollyg** [comment]
@fabled would you care to comment on #323 - have you ever seen c_ip() return multiple IPs?

**Comment by JeroenvIS** [comment]
In can't remember seeing c_ip() ever returning an array of management addresses, ie returning multiple IPv4 addresses for the same neighbour key.

In my experience, if two devices advertise multiple neighbour relations to each other (for example, if an interface is configured with logical sub-interfaces), then each neighbour relation has its own key in c_ip() and/or in lldp_addr().

Where it _does_ get interesting is when such a neighbour relation advertises a management address per address family. That's what lldp_ip(), lldp_ipv6() and lldp_mac() are for. I can provide example outputs to show how those methods relate to each other; preferably not public because I'd have to remove a lot of potentially sensitive information from the outputs.

**Comment by ollyg** [comment]
Thanks @JeroenvIS this helps.
