### ISSUE TITLE
Question: Is it possible to have a distributed deployment ?

### ISSUE THREAD

**Issue by ikus060** [netdisco/netdisco#313]
Hello,

I'm currently evaluating Netdisco to check if it meet our requirements. I've search a bit for documentation related to this, but it's ratter unclear and most of the time it's related to Netdisco v1 instead of v2. I want to know if its 'possible to have a distributed environment.

i.e.  I want to install workers on multiple separate servers.
For various security reason, it's impossible for us to a a single server with a management link that can access all our devices. So I would like to have 3 servers (one in each zone) plus another one to consolidate all the topology retreive.

Would be be possible ?

**Comment by ollyg** [comment]
Hi,

Yes this is definitely possible (with your scenario of security domains/zones as the use case). In Netdisco 2 you can run multiple backend daemons with different configurations (for SNMP communities, etc). You will always need one database that they all connect to.

So, follow the regular install instructions on each node (but only install PostgreSQL once). On the web server, start the netdisco-web daemon. On the poller/worker servers, start netdisco-daemon (or netdisco-backend in a future release). As I said, you can also change the config on each so that they only have the local SNMP community settings.

I am not sure you can consolidate the topology from one location. The topology is gathered from the LLDP/CDP/etc neighbor tables on each device during the "discover" job. Let me know if I have misunderstood the question.

I hope this makes sense.

regards,
Oliver.

**Comment by ollyg** [comment]
I forgot to mention that you can use discover_no/macsuck_no/arpnip_no configuration to control which devices are polled by each server.

**Comment by ollyg** [comment]
Or indeed discover_only/macsuck_only/arpnip_only (I shall put this in the documentation!).

**Comment by ikus060** [comment]
Thanks for the help. I will try to setup something similar in our lab.

How is Netdisco know witch deamon should be used to make the discovery. e.g.: Zone1 is 172.12.3.0/24, Zone2 is 10.255.0.0/24 and Zone3 is 142.96.0.0/16

Is it possible to control this using the `discover_no` ? If so, is it possible to provide a small example ?

**Comment by ollyg** [comment]
You can use `*_only` configuration to control the workers. So you should configure these settings on each backend: discover_only, macsuck_only, arpnip_only, to contain the prefixes for each zone:

```
# backend 1:
discover_only: [ '172.12.3.0/24' ]
macsuck_only: [ '172.12.3.0/24' ]
arpnip_only: [ '172.12.3.0/24' ]

# backend 2:
discover_only: [ '10.255.0.0/24' ]
macsuck_only: [ '10.255.0.0/24' ]
arpnip_only: [ '10.255.0.0/24' ]

# backend 3:
discover_only: [ '142.96.0.0/16' ]
macsuck_only: [ '142.96.0.0/16' ]
arpnip_only: [ '142.96.0.0/16' ]
```

Then just start the three backend daemons, and the web frontend daemon somewhere as well. All backends will connect to the database to take jobs from the queue, but they only act on the ones that they have permission for.

(In the next version of Netdisco this will be smarter and more efficient, and it will be possible to create a named group so there's a bit less repetition if you have several prefixes for each zone - but I don't know when that will be released.)

regards,
oliver.

**Comment by ollyg** [comment]
See also the new devices_no and devices_only settings in the current Netdisco release.
