### ISSUE TITLE
No bp_index found on Cisco 3750X stack

### ISSUE THREAD

**Issue by eacheach** [netdisco/netdisco#339]
When macsucking a stack of Cisco 3750X switches we noticed that we weren't getting good data.  When we debugged it, we saw that macsuck was having an issue mapping bp_index.  I asked for some help on the mailing list and was asked for additional debug info to be posted here.

## Expected Behavior
We expect to see the port associated with a given mac address in Netdisco.

## Current Behavior
Even though the switch is discovered, the mac address is not associated with the port in Netdisco

## Possible Solution
None

## Steps to Reproduce (for bugs)
Macsuck a Cisco 3750X stack?

## Context
See attached netdiso.issue.txt
[netdisco.issue.txt](https://github.com/netdisco/netdisco/files/1231749/netdisco.issue.txt)
 file.

## Your Environment
App::Netdisco	2.36.3
SNMP::Info	3.35
DB Schema	44
PostgreSQL	9.2.18
Perl		5.16.3

**Comment by ollyg** [comment]
Hi @eacheach 
That's a very good analysis, thank you! It seems to me that there are some entries missing from the tables. There is not a lot we can do about that (do you think your vendor or support partner might be able to advise?).
Having said that, @JeroenvIS knows a *lot* more about this than me, and when he's back from vacation might want to take a look. Also, I note you switch from 4/0/24 to 4/0/34 during the analysis but I don't know if that was intentional.
regards,
Oliver

**Comment by JeroenvIS** [comment]
Indeed, that's a good set of data to start from.

I notice that you're using SNMPv3, and there seem to be some discrepancies between the data that you got from the macsuck and the fw_port dump. The fw_port dump is a lot more terse than I'd expect, and it doesn't include the mapping for your MAC pointing to bridge port 205. The macsuck debug output probably had some lines indicating that it was retrieving forwarding tables per VLAN, using community-based indexing or SNMPv3 contexts? Could you attach this debug output, or does it contain too much sensitive information?

The snmpwalk for BRIDGE-MIB::dot1dBasePortIfIndex and the bp_index dump match, so that's a good sign.

Just to be sure, @eacheach : you did configure your 3750 stack for SNMP access to each VLAN context, as noted in https://metacpan.org/pod/distribution/App-Netdisco/lib/App/Netdisco/Manual/Vendors.pod#SNMPv3-Support-on-Cisco-IOS ?

Could it be that the interfaces currently listed in the bp_index dump / BRIDGE-MIB::dot1dBasePortIfIndex snmpwalk all have something in common, eg all carry VLAN 1?

Could be that some IOS versions also need community-based indexing (or VLAN context mapping) for providing a full list of bp_index mappings. I'd be very interested in seeing an snmpwalk for BRIDGE-MIB::dot1dBasePortIfIndex, using the context associated with the access VLAN for your example port. And if that doesn't work, it's worth trying with SNMP v2c as well, to rule out an SNMPv3 vs v2 bug on the switch.

**Comment by eacheach** [comment]
The configuration matches well with your example.  It's basically the same snmp-server config that's on all our devices (most of which are not having any issues).  I missed a key line in the debug output.  Right before the bp_index match failure for a given vlan, I get the following:
SNMP::Info::_load_attr bp_index : BRIDGE-MIB::dot1dBasePortIfIndex : .1.3.6.1.2.1.17.1.4.1.2
SNMP::Info::_load_atrr: BULKWALK Timeout at /home/netdisco/perl5/lib/perl5/App/Netdisco/Core/Macsuck.pm line 306.

Which is:
  my $bp_index = $snmp->bp_index;

These 3750X's are notoriously sluggish with regard to SNMP polling.  Is there a ""correct" way to extend the timeout to see if that resolves the issue?

**Comment by eacheach** [comment]
I can confirm that the missing bp_index mapping of 205 on vlan 104 is in fact populated if I set the appropriate context.  The command also takes 13 seconds to run on this vlan with multiple couple second hangs which I suspect is the issue.

time snmpwalk -v3 -u redacted -A redacted -l AuthPriv -a SHA -x AES -X redacted -n vlan-104 172.16.252.70 BRIDGE-MIB::dot1dBasePortIfIndex
...
BRIDGE-MIB::dot1dBasePortIfIndex.205 = INTEGER: 11637
...
real	0m13.317s
user	0m0.061s
sys	0m0.011s

**Comment by ollyg** [comment]
There's an snmptimeout config setting which I think defaults to one second.

**Comment by eacheach** [comment]
That resolved the issue.  Thanks for your time on this.  I set it to 4 seconds for now and will play with tuning a bit.  Since macsuck_no_vlan documentation suggests that this can be an issue for some vlans, maybe a macsuck_snmptimeout to use the longer timeout only when necessary may be nice option to have.  From the configuration docs it looks like there was a legacy v1 config item called macsuck_timeout.  Did macsuck_timeout do this?

**Comment by ollyg** [comment]
Thanks for letting us know @eacheach and I'm really pleased we got to the bottom of it.

Yes the macsuck_timeout setting probably would help, and is not yet implemented. It could probably be done without too much difficulty.
