### ISSUE TITLE
Extend Cisco-specific PortFast info to other devices classes

### ISSUE THREAD

**Issue by JeroenvIS** [netdisco/netdisco#384]
## Expected Behavior

Improvement: with #12 the Cisco specific "PostFast" status is collected and stored, but the more generic version is not implemented. The comment by @fenner, indicating that RSTP-MIB was quite recent and might not be widely supported, was 10 years ago; it has been very widely adopted since then.

I suggest we improve this feature by first trying to fetch the IEEE equivalent(s) of Cisco PortFast, and fall back to trying to fetch the vendor-specific PortFast only of the IEEE equivalents are not available.

## Possible Solution

Small change to SNMP::Info first, eg add appropriate methods from RSTP-MIB and possibly IEEE8021-MSTP-MIB into Bridge.pm; then update Netdisco to collect that data.

## Steps to Reproduce (for bugs)

1. 
2. 
3. 
4. 

## Context

I try to keep Netdisco multi-vendor where possible ;)

From very preliminary data gathering, I'd say we should prefer the IEEE *AdminEdgePort objects over the *OperEdgePorts; at least in my environment, ports that are down may show that OperEdge is disabled, while the actual configuration (AdminEdge) is enabled. So IMHO *AdminEdgePort values give a better indication of the port config, where *OperEdge status is more likely to have minor implementation issues across vendors (eg only being meaningful when port is up).

## Your Environment

* Netdisco version used: 
* SNMP::Info version used:

**Comment by ollyg** [comment]
Yep, totally agree. I did the Netdisco side and we have an API to clone on the SNMP::Info side.

I wasn't able to implement RSTP-MIB because I don't seem to have a device supporting it for FastStart (so it's not *that* widely supported ;-)). I did add RSTP-MIB to Bridge.pm but no more.

I don't have an opinion whether Admin or Oper status is preferred for storing in Netdisco.

This ticket should be in SNMP::Info, as this is now internal work for that dist, so I'll move it there.
