### ISSUE TITLE
Enhancement suggestion: add EAP (802.1X) info 

### ISSUE THREAD

**Issue by pilyon3** [netdisco/netdisco#412]
Hi,

All is in the title. I didn't see this feature in netdisco (but maybe I'm wrong). Is it possible to add it ?

These infos could be interesting:
- EAP global status/capability
- EAP configuration status for ports: authorized, non-authorized, auto

However, I'm not sure that gathering connected user/mac would be a good idea nor moreover that this one could be easly feasible.

**Comment by ollyg** [comment]
First place to look is the MIB table with the info... is this `IEEE8021-PAE-MIB` ??

We can easily do the Netdisco part... it can be appended to the "extended port info" we gather currently for RSTP Fast Start (portfast).

**Comment by pilyon3** [comment]
Yes, it is this one.

**Comment by JeroenvIS** [comment]
If we implement this, IMHO we should seriously consider also adding details about MAC-based and/or web-based auth if that's enabled. For LAN networks with dynamic authorization on ports, usually 802.1X is configured with MAC auth bypass or web auth as fallbacks for clients that don't support 802.1X and/or in order to support unmanaged / BYOD clients.

For Cisco and HPE/Aruba (former ProCurve) I know the relevant MIBs pretty well, so maybe I can help out there.

**Comment by jeneric** [comment]
+1 for the feature.
I'm most interested in the connected user/mac which I believe we would display in the node search results.

**Comment by ob1kenob** [comment]
This would be extremely useful for my environment/install as well.
