### ISSUE TITLE
More device colours in the Neighbors view

### ISSUE THREAD

**Issue by netdisco-automation** [netdisco/netdisco#43]
Hi I like to see not only IP address, but also the system name in map. 

I was able to find a line where I can add a string - line 136 in ./views/ajax/device/netmap.tt

but I do found not where the query to device table is...

Reported by: dedkus

Original Ticket: [netdisco/nd2-features/45](https://sourceforge.net/p/netdisco/nd2-features/45)

**Comment by vbep** [comment]
Hi, I'm not seeing name displayed in topology map - only IP - except in the case of pseudo devices. Have I missed configuration? Sorry for necro, figured it was best to tack it on here. Please advise.

**Comment by ollyg** [comment]
Hi vbep - do you see DNS names for devices when you look for them in the inventory and other locaitons in Netdisco?

**Comment by vbep** [comment]
Hey ollyg thanks for the reply. Short answer, "no". I was expecting to see snmp device name.

However, I saw a note about it using dns names somewhere so I've done a test with one switch. Added the IP to AD DNS (the same dns server the netdisco box is set to use), and done a fresh discover on the switch in question, the dns name is not being listed on the Addresses tab.

What have I missed? Thanks.

**Comment by vbep** [comment]
Ollyg, thanks for the help, the problem was the PTR. Is there any way to display the SNMP device name on the topology map rather than rely on DNS ? Thanks again.

**Comment by ollyg** [comment]
Hi vbep,
Looks like the code currently tries DNS and falls back to IP. We have the place in the code where it should happen:
https://github.com/netdisco/netdisco/blob/2.035006/lib/App/Netdisco/Web/Plugin/Device/Neighbors.pm#L17
However it might be a non-trivial patch so that the data is pulled from the DB in an efficient way rather than one-at-a-time.
We should have another ticket for this, so I created:
https://github.com/netdisco/netdisco/issues/316
Thanks,
Oliver.

**Comment by ollyg** [comment]
I believe the new netmap we have should address all these questions!
