### ISSUE TITLE
Need help with "node monitor"

### ISSUE THREAD

**Issue by MarcusCaepio** [netdisco/netdisco#452]
Hi all,
I just started to use netdisco and being interested in the node monitor. 
I have configured a MAC I want to monitor, disconnected the node, made a discover, connected again and discovered again. I did not get any mail. 
How is the node monitor working and what are the requirements to get mails? Do I have to install / configure sth. additional to get mails?

Thanks in advanced

**Comment by inphobia** [comment]
looking at https://github.com/netdisco/netdisco/blob/master/lib/App/Netdisco/Util/NodeMonitor.pm it seems to be using sendmail on the local system.

the sendmail path seems to be hardcoded to /usr/sbin/sendmail it seems. so i guess the first check would be to see if that binary is present.

second step would be to check if your mailer install is working. on the commandprompt type:
sendmail your@email.address
testmail
.


so that's sendmail to start the mail client. then: testmail _enter_ . _enter_

if you dont get that mail your mailerconfig is the problem.
