### ISSUE TITLE
Should renumber care if the device already has the new IP as an alias?

### ISSUE THREAD

**Issue by ollyg** [netdisco/netdisco#506]

**Comment by inphobia** [comment]
for the device_ip table? i don't think it matters there since it has an entry for defined ip as an alias as well.

device_ip.ip should match on a device_ip.alias entry.

| ip        | alias     | subnet      | port                      | dns  | creation                   |
|-----------|-----------|-------------|---------------------------|------|----------------------------|
| 10.6.10.3 | 10.6.10.3 | 10.6.0.0/16 | TenGigabitEthernet0/0/1.6 | NULL | 2019-03-02 17:02:24.837944 |


and as the renumber disclaimer says: no further checks are done.

**Comment by ollyg** [comment]
Fixed in:
[master ef560fb5] #506 relax device renumber so it works for an alias
