### ISSUE TITLE
Excluding IP phones from discovery

### ISSUE THREAD

**Issue by rkerr** [netdisco/netdisco#512]
This is basically re-opening of issue #444, as I think my comment after it was closed got lost in the noise.

## Expected Behavior

'IP Phone' or 'AP' in discover_no_type should exclude phones or APs from discovery, as it did prior to commit e1b9f22

## Current Behavior

These strings in discover_no_type have no effect.

## Possible Solution

Re-instate the code that modified remote_type based on remote_cap - or provide an alternative method to exclude devices from discovery based on remote_cap.

**Comment by ollyg** [comment]
See also https://github.com/netdisco/netdisco/wiki/_compare/fba9ad1..29f7b7c

**Comment by inphobia** [comment]
are your phones still showing a phone icon next to them? if so that means device_port_properties should have remote_is_phone set which we could use. however, device_port_properties is at the end of the discover queue, and neighbor discovery at the start.

perhaps an elegant solution would be to something like the property regex (https://github.com/netdisco/netdisco/wiki/Configuration#access-control-lists) but which can match agains lldp/cdp/other discovery protocols instead. an actual use would be to ignore systems based on known buggy software, which can be gotten from lldp_rem_sw_rev() for example. downside is to match against those properties we will also need to request them first, adding to network load.

**Comment by rkerr** [comment]
Yes they still have the correct icon, it's just the discover_no logic that's changed as far as I can tell.

Whilst what you describe with the property regex would be nice I suspect it would be a bit of a nightmare to do. There's so many different discovery protocols and no consistent format to many of the values. Mapping all the properties consistently across protocols and devices doesn't sound easy.

**Comment by inphobia** [comment]
> Mapping all the properties consistently across protocols and devices doesn't sound easy.

it's not, hopefully that's where we come in 🙏 

if i read #444 correctly your devices have limited lldp support. do they support any other discovery protocols (i guess that means cdp only haven't seen any of the other ones actually in the wild)?

secondly, what lldp info do they provide? can you have a look at https://metacpan.org/pod/SNMP::Info::LLDP#LLDP-Remote-Table-(lldpRemTable) and report for just 1 phone?

side note: the property regex doesn't have to be complicated, if i read the old code correctly it just searched for the string "telephone":
`if scalar grep {defined && m/^telephone$/} @{ $lldp_cap->{$idx} };`

**Comment by ollyg** [comment]
Hi @rkerr my apologies for this regression. I thought about how best to fix this, and settled on two new settings. You should set `discover_phones:false` and `discover_waps:false` if you want to suppress discovery of these. The `discover_no_type` setting will now default to an empty list. The new settings use the `phone_platforms` and `wap_platforms` settings, which can be amended by you.

[master 09d29954] #512 fix regression in phone/wap discovery exclusion

**Comment by rkerr** [comment]
Can confirm discover_phones: false and discover_waps: flase seems to work fine

**Comment by ollyg** [comment]
Thanks! :-D
