### ISSUE TITLE
need a way to detect collection timeouts

### ISSUE THREAD

**Issue by inphobia** [netdisco/netdisco#525]
in relation to #227 

netdisco (and snmp::info too perhaps) need a way to detect and propagate timeouts. preferably not only for snmp but for all Lib/Transport classes.

endgoal is to handle incomplete devices or discoveries more graceful, perhaps on a seperate page (like snmp connect timeouts) or with a notice on the device page,

mockup:
![image](https://user-images.githubusercontent.com/39005454/53688804-d9f30480-3d49-11e9-9e53-7c10a2cfe867.png)4

## Expected Behavior

either do not store incomplete results or at least let users know if we hit timeouts.

## Current Behavior

it seems the database might become populated with incomplete results, on cisco stacks i noticed this with poe info in the past.

## Possible Solution

detect & handle timeouts, but how & where?

## Steps to Reproduce (for bugs)

1. 
2. 
3. 
4. 

## Context

i used to see this a lot on cisco375xx, where timeouts seem to be common in stack setups, and with snmpv3 and/or vrf on other devices i hit this issue too.
it would be easier for us to troubleshoot and provide a clearer user experience if  we could somehow inform of incomplete results.

## Your Environment

* Netdisco version used: HEAD
* SNMP::Info version used: 3.65

**Comment by ollyg** [comment]
The reason why #227 stalled (and it might be worth continuing that ticket rather than starting this one, as this seems just to be a potential solution for the other?) is that it's difficult (for me, at least) to define what "correct data returned" is. Some tables are necessary, some are optional, and Netdisco can often store useful info even with partial or missing tables.

Anyway, yes we could do this by, for example, wrapping some calls to SNMP::Info (in Netdisco) such that an exception is thrown if the returning hash is empty. Run the call or set of calls in a try/catch block, and then if the exception is caught we abort the job (or part of job).

@inphobia please would you have either this ticket or #227 open but not both? Thanks.

**Comment by inphobia** [comment]
> it's difficult (for me, at least) to define what "correct data returned" is. Some tables are necessary, some are optional, and Netdisco can often store useful info even with partial or missing tables.

i agree with that wholeheartedly. i don't think there is any easy way of knowing if the returned data is complete or correct,
however, if you know snmp or ssh timed out you can be quite certain that it's the opposite; not complete.

> @inphobia please would you have either this ticket or #227 open but not both? Thanks.

perhaps this is more a wishlist thing, i'll add it there.
