### ISSUE TITLE
Use ACL in schedule to select set of target devices

### ISSUE THREAD

**Issue by ollyg** [netdisco/netdisco#580]

**Comment by inphobia** [comment]
disregard, just writing this comment to get a github email reply link

**Comment by inphobia** [comment]
Anybody?

On Thu, 9 May 2019 at 21:32, Pavel Skovajsa <pavel.skovajsa@gmail.com> wrote:
Hello,
Can somebody help me with figuring out how the ACLs are supposed to be used, I have a feeling I am not doing this correctly.

Currently due to the sheer number of devices we are running only 1 macsuck and arpnip per day. For a specific group of devices (the fr003 group I just created, see below) I am trying to change the schedule so that it runs more frequently, but somehow I am doing something wrong since it is not being run more frequently. Here is the important part of the config:

host_groups:
        fr003:
        - !!perl/regexp ^(?i)fw003-.*$
        - !!perl/regexp ^(?i)FRDH.*$


schedule:
  macwalk:
    when: '20 21 * * *'
  arpwalk:
    when: '50 8 * * *'
  macwalk_specific:
    action: macsuck
    when: '15,45 * * * *'
    device: 'group:fr003'
 arpwalk_specific:
    action: arpwalk
    when: '0,30 * * * *'
    device: 'group:fr003'

Thanks,
Pavel

________________________________

Volg Aquafin op Facebook<https://www.facebook.com/AquafinNV> | Twitter<https://twitter.com/aquafinnv> | YouTube<http://www.youtube.com/channel/UCk_4P5BJ-MtEEDCkCsR_KqQ?feature=mhee> | LinkedIN<http://www.linkedin.com/company/aquafin/products> | Instagram<https://www.instagram.com/aquafin_nv/>

In het kader van de uitoefening van onze taken verzamelen we bij Aquafin persoonsgegevens. Hoe we omgaan met deze gegevens en wat de rechten van de betrokkenen zijn, kan je nalezen in onze privacy policy<https://www.aquafin.be/nl-be/privacy-policy>.

  P Denk aan het milieu. Druk deze mail niet onnodig af.

**Comment by ollyg** [comment]
I tried to implement this but got stuck because PostgreSQL can't understand the regular expressions.

I've added this to the wishlist page and we can revisit later: https://github.com/netdisco/netdisco/wiki/Wishlist

**Comment by ollyg** [comment]
implemented in release 2.067000!
