### ISSUE TITLE
Request for posting: Instructions for installing the NetDisco container on an Ubuntu host

### ISSUE THREAD

**Issue by StewAlexanderACC** [netdisco/netdisco#619]
It took some time to build this doc, think it would be useful for others to have:

![image](https://user-images.githubusercontent.com/48565067/60982951-1beb1300-a307-11e9-848f-466a21e02ea1.png)
-----------
![image](https://user-images.githubusercontent.com/48565067/60982995-358c5a80-a307-11e9-8f07-e4e9b71a837a.png)
---------------------
![image](https://user-images.githubusercontent.com/48565067/60983070-518ffc00-a307-11e9-91cc-9ee04b5ef06d.png)
------------
![image](https://user-images.githubusercontent.com/48565067/60983102-62d90880-a307-11e9-9fd0-371d43b99070.png)

**Comment by inphobia** [comment]
thx for the writeup, i'll see if i can set some time aside in the coming weeks to update the docs & test this on a few different distro's.

note to self:
* check how/if multiple containers interact. how about containers ending in _1 etc ( netdisco/netdisco-docker#17 )
* note minimal docker / docker-compose / etc versions in docs
* try & fix netdisco/netdisco-docker#14 while doing these tests

(pdf found here netdisco/netdisco-docker#18, also by @StewAlexanderACC )

**Comment by StewAlexanderACC** [comment]
Wrote it up here too @inphobia : https://github.com/StewAlexanderACC/NetDisco-Ubuntu-Install

**Comment by StewAlexanderACC** [comment]
@inphobia Any updates?

**Comment by inphobia** [comment]
it mostly made me realize i need to move "learn more docker stuff" higher on my prio list.

i'm not quite sure about https://github.com/StewAlexanderACC/NetDisco-Ubuntu-Install/blob/master/README.md#initial-setup however. https://metacpan.org/pod/App::Netdisco#First-Run should be all you need to get netdisco doing everything even on docker, if it doesn't then i would consider it a bug.

for this specific issue i like the idea of some more operating specific instructions (like we do for normal deployments already: https://metacpan.org/pod/App::Netdisco#Dependencies) to get the basics up & running. the other clarifications i would like to integrate in our mainline docs and if needed go into more detail there (no_auth configuration for example), as to not duplicate information.

but to get there i think we first need to resolve some of the questions which this ticket inspired, i'm thinking of what's discussed here:
 - netdisco/netdisco-docker#19
 - netdisco/netdisco-docker#23
 - netdisco/netdisco-docker#24

the second takeaway is that a few more screenshots in our docs wouldn't hurt, as seen in your pdf here: https://github.com/netdisco/netdisco-docker/issues/18#issuecomment-512246884

personally i don't think i'll be able to work on this until at least the beginning of next year due to serious lack of time. perhaps the best solution until we decide on the above issues is to add a `contrib` directory the docker repo with your writeup, or somehow link to it so it gets some more exposure.

seems i ended up with even more questions as we begun with 😄 , perhaps @netdisco/netdisco-developers can provide some input on how to move forward?

**Comment by ollyg** [comment]
Thanks @StewAlexanderACC I have added a link to your doc from our install tips guide:
https://github.com/netdisco/netdisco/wiki/Install-Tips#docker-install-guide-for-ubuntu

**Comment by StewAlexanderACC** [comment]
@ollyg - thanks
