### ISSUE TITLE
Color by Throughput not showing data

### ISSUE THREAD

**Issue by def-bs** [netdisco/netdisco#626]
## Expected Behavior
I discover an option in the map, in the lower part you can choose "Color By", there are three options: Throughput, Host Group, Location.

By default, it is selected Throughput, but nothing is shown.

I expect that with Throughput, in the lower corner of the map I will be able to see the Throughput.

## Current Behavior
If I selected "Color By" with Host Group. I get this in the lower corner:
![Schermata a 2019-07-19 11-07-11](https://user-images.githubusercontent.com/31916347/61523856-71b17080-aa15-11e9-9915-47afae37f697.png)

The same happens with Location, but Throughput is empty.

## Possible Solution
I would like to know if it is a bug or it has been designed to work in this way.

## Steps to Reproduce (for bugs)
1. Select a device
2. Go in the Map section
3. Change the Color By attribute

## Your Environment
App::Netdisco 	2.42.10
SNMP::Info 	3.68
DB Schema 	58
PostgreSQL 	9.6.13
Perl 	5.24.1

Thank you a lot.
Best Regards.

**Comment by ollyg** [comment]
Hi! Sorry this isn’t clear, but it’s by design this way.

The throughput doesn’t have a key as the values are synthetic and simply based on the total ports and aggregate port speed. It’s not a meaningful thing to show the user, I believe. Sorry about that.

**Comment by FabioPedretti** [comment]
I think at least a simple legend should be shown, otherwise the colors have no meaning, e.g. it is not clear if a "red" is better or worse than a "green".

Alternatively the "Throughput" classification could be reworked using the average speed (red <= 100Mb/s, blue <= 1Gb/s, and so on).

Thanks.

**Comment by inphobia** [comment]
well, you could always have a look at \lib\App\Netdisco\Web\Plugin\Device\Neighbors.pm if you feel like it, the code doesn't seem that complicated. but there are quite some options to consider 😈 ,  see for the non high speed ones: https://github.com/netdisco/snmp-info/blob/cefbcce8e3c6e207b7f043946f6ced6922d11aa6/lib/SNMP/Info.pm#L3629

graphing is one of the features i use most to show collegues how usefull netdisco is, but it could use some love. i'm gathering ideas here: https://github.com/netdisco/netdisco/projects/5 ; feel free to have your say.

i'm do want to point out the we also support graphviz (commandline only atm, and it can be quite arcane to start with. that would fit your needs if interactive maps aren't required)


here's the only example i have atm since i'm trying to move us over to graphviz2. lines are different colors depending on speed, size of device is number of ports (  no legend on the map yet, still early wip)
![image](https://user-images.githubusercontent.com/39005454/62580837-99268b00-b8a7-11e9-900f-872a9a92f7d4.png)
