### ISSUE TITLE
host_group_displaynames search

### ISSUE THREAD

**Issue by DerPhlipsi** [netdisco/netdisco#684]
## Expected Behavior

Currently, the host groups list in the WebUI is a simple scrollable selection box.

## Current Behavior

With larger environments, the host groups list in the WebUI becomes cumbersome. It's searchable by the search function of the browser, but that feels like a unclean workaround.

## Context

This is coming from #683 as a side idea.

**Comment by inphobia** [comment]
i think i can boil down your question to: lists should be resizable in the webui. i'm running into that as well with online graphs, since `SELECT COUNT(DISTINCT location) FROM device;` is returning 713.

i'm guessing something like (for example) what github does with issue comments would be what you could use?
![image](https://user-images.githubusercontent.com/39005454/70381417-14797580-194a-11ea-8efe-099f4e14e0d5.png)

i'm not sure if that possible without a lot of hacks in our current web framework. i'd like to move netdisco2 to a frontend framework we can maintain easily (https://github.com/netdisco/netdisco/projects/6) once we start on netdisco3. this seems like something that could be added to the wishlist.

**Comment by ollyg** [comment]
We do have autocomplete functionality in some boxes eg the titlebar global search, so we could use that. I would need to think a bit more about how to have that *and* the list selector.

**Comment by ollyg** [comment]
I've added this to the wishlist page https://github.com/netdisco/netdisco/wiki/Wishlist/_edit
