### ISSUE TITLE
host_groups subgroups

### ISSUE THREAD

**Issue by DerPhlipsi** [netdisco/netdisco#685]
## Expected Behavior

Subgroups can either be defined in the config-yaml (as subitem of it's parent or with a property referencing its parent) or are dynamically created for group names that matches in the x first characters and take these x characters as name, and are only displayed on the WebUI after the parent group was clicked in the list.

## Current Behavior

Every host group is displayed, enlarging the list if there are plenty of them.

## Context

Host Groups are a valuable feature, especially for multiple sites or keeping maps clean.
With larger sites, e.g. having the need for multiple maps, the host group list becomes cluttered. Having sub groups solves this issue.

**Comment by ollyg** [comment]
Thanks for the suggestion @DerPhlipsi but I'm not sure this one will be implemented soon.

What you're getting at is really something like VRF or device domains which we do want to do (multi site and multi tenancy) but it'll have to be in Netdisco 3 as it's a major rewrite to a lot of the logic in Netdisco.

Alternatively if you can expand on the Expected Behaviour it might help realise a simpler implementation.
