### ISSUE TITLE
RancidConf with host_groups exclusion

### ISSUE THREAD

**Issue by cromra** [netdisco/netdisco#686]
I'm trying to generate a list of network equipments for rancid with the new RancidConf module, and i'm trying to exclude some network equipments based with their name starting by MYPREFIX.
Here is the configuration portion i use :
 
host_groups:
  myexcludedgroup:
    - 'name:^MYPREFIX.*$'
rancid:
  rancid_conf: /home/rancid/etc
  excluded:
    test: 'group:myexcludedgroup'

When i type ~/bin/netdisco-do makerancidconf -D i get all my devices, including the ones i do not want, and the debug flag does not really help me see the reason (no specific output).

Could anyone point me to the right direction : am i doing my host_group correctly for example ?
Thanks a lot

**Comment by inphobia** [comment]
this could be yaml parsing, whitespace matters there. did you try:

```yaml
host_groups:
  myexcludedgroup:
    - 'name:MYPREFIX.*'
rancid:
  rancid_conf: '/home/rancid/etc'
  excluded:
    exgroup1: 'group:myexcludedgroup'
```

**Comment by cromra** [comment]
I triple checked (and used a yaml validator, the file seems ok.
The only point i see is if i misinterpreteded that the 'name' field is the 'System Name' of my device in netdisco.

**Comment by inphobia** [comment]
so does this mean that it's working as expected or are you still having issues? if so, here is some additional info alrdy.

the properties you can match with (as `name` in the yaml example) are column names in the device table. it's documented under `property:regexp` here https://github.com/netdisco/netdisco/wiki/Configuration#access-control-lists (could use some reformatting but need to think about clear wording first).

so depending on what you mean with 
> exclude some network equipments based with their **name**

 - the `name` column comes via snmp::info->name() and will most likely be whatever the device returns in response to an snmp `sysName` query.
 - the `dns` column will contain whatever a reverse dns lookup (ptr record) returns for the the main ip of the device, if no ptr record exists it will be set to null.

some of these can be manually tweaked as noted here:
 - https://github.com/netdisco/netdisco/wiki/Troubleshooting#devices-have-the-wrong-names
 - https://github.com/netdisco/netdisco/wiki/Configuration#device_identity

netdisco's `system name` is in the web interface is indeed the `name` field in the device table, i don't think we have go into that much detail in our docs as to which fields in the web interface are gotten from which database data.

i hope this gives a basic idea on how it works. let us know what exactly you mean by `name` & then we'll go from there.

**Comment by cromra** [comment]
I'm still having the issue, and i've managed the regex part.
I added a fake vendormap rule to test my host_groups grp-isprtr, and it works : "i get the hp" for the designated routers. But there are not excluded (even when i remove the vendormap part).
My remaining concern is the "exgroup" name, that i didn't get if it had to map to something.
`
host_groups:
  grp-isprtr: 'name:^ISP.*'
  grp-ciscosb:   'os:ros'
rancid:
  rancid_conf: '/home/rancid/etc'
  excluded:
    exgroup: 'group:grp-isprtr'
  vendormap:
    cisco-sb: 'group:grp-ciscosb'
    hp: 'group:grp-isprtr'
`

**Comment by inphobia** [comment]
i'll need to take a closer look at how `check_acl_no` works:
https://github.com/netdisco/netdisco/blob/b211c7c7e20c812319f407f348eeb044297c54eb/lib/App/Netdisco/Worker/Plugin/MakeRancidConf.pm#L62


wonder if it's interpreting the excluded list as a setting instead of an acl...

https://github.com/netdisco/netdisco/blob/b211c7c7e20c812319f407f348eeb044297c54eb/lib/App/Netdisco/Util/Permission.pm#L29-L36


if at al possible could you provide us with a debug output? (netdisco-do makerancidconf -D -d ipaddr), if you don't want to make it public you can either link it in the irc channel or mail it to me.

**Comment by cromra** [comment]
Please tell me which mail address i can send it to.

**Comment by inphobia** [comment]
nick.nauwelaerts _at_ aquafin.be

**Comment by inphobia** [comment]
working in this in private mail with @cromra

**Comment by ollyg** [comment]
Hi, I found that this is a bug in both the documentation and implementation of the Excludes feature of MakeRancidConf. Sorry for that. The issue is that the Excludes setting must be a list ACL, not a dictionary of ACLs.

The bug is fixed in the next release, and MakeRancidConf will be backwards (or bugwards) compatible with the old documented config if used. 

[master e42c2135] fix #686 makerancidconf excluded setting should be (ACL) list not dict

**Comment by ollyg** [comment]
So your config should be:
````
host_groups:
  grp-isprtr: 'name:^ISP.*'
  grp-ciscosb:   'os:ros'
rancid:
  rancid_conf: '/home/rancid/etc'
  excluded: 'group:grp-isprtr'
  vendormap:
    cisco-sb: 'group:grp-ciscosb'
    hp: 'group:grp-isprtr'
````

**Comment by cromra** [comment]
Thanks a lot, it works perfectly with the fix
