### ISSUE TITLE
VLAN inventory count is not correct

### ISSUE THREAD

**Issue by def-bs** [netdisco/netdisco#688]
## Expected Behavior

Dear netdisco,

I noticed that the VLAN count is not correct, when I select a specific VLAN, the device count that is shown is not the same.

## Current Behavior

I select a VLAN from VLAN invetory, on the main page is shown a number, but inside there is a different number of devices.

## Your Environment

Software 	Version
App::Netdisco 	2.44.4
SNMP::Info 	3.70
DB Schema 	61
PostgreSQL 	9.6.15
Perl 	5.24.1

Best Regards.

**Comment by inphobia** [comment]
how do you select the vlan, by name or number?


it seems i'm able to reproduce it, when i go to report->vlan inventory and look at all vlans with id 2:
![image](https://user-images.githubusercontent.com/39005454/70191705-f1f11d80-16f9-11ea-9ecc-b9f4705abee1.png)

in total 75 devices.

however when i click the "2" it all of the sudden mentions 80 devices.

**Comment by inphobia** [comment]
disregard the previous screenshot, it's from my production setup. could reproduce it on my test setup in a few minutes:

the vlan in question i'm missing is:: vlan id `2` - name `data`

![image](https://user-images.githubusercontent.com/39005454/70192508-37aee580-16fc-11ea-90be-32eaaff1e8c6.png)

however it's know in device_vlan:
![image](https://user-images.githubusercontent.com/39005454/70192531-51e8c380-16fc-11ea-89aa-8c863d43da74.png)

but while it's defined on the device, it's not actually in use:
![image](https://user-images.githubusercontent.com/39005454/70192566-72188280-16fc-11ea-9b6b-61183edac7ca.png)

![image](https://user-images.githubusercontent.com/39005454/70192596-8a889d00-16fc-11ea-8901-06cf6e1f3b0c.png)

at first glance it seems the vlan report does not include vlans which are defined but not configured on any port, but need to have a closer look at 

https://github.com/netdisco/netdisco/blob/b211c7c7e20c812319f407f348eeb044297c54eb/lib/App/Netdisco/Web/Plugin/Report/VlanInventory.pm#L18-L33

**Comment by def-bs** [comment]
Sorry for the late answer, i didn't get any e-mail notification.

I see this:
![Schermata a 2019-12-09 12-56-34](https://user-images.githubusercontent.com/31916347/70434026-71c51200-1a83-11ea-85c2-2b818627cd05.png)


But if i go inside, i get two devices:
![Schermata a 2019-12-09 12-57-53](https://user-images.githubusercontent.com/31916347/70434071-8903ff80-1a83-11ea-8cf1-877cca22f755.png)


But there are a lot of this cases.

**Comment by ollyg** [comment]
Hi @def-bs thanks for raising this issue. As @inphobia very helpfully and correctly showed, the inventory report is based on actual active ports, but then you are clicking through to the plain VLAN search which shows all devices carrying the VLAN (even those with zero ports configured, which is where the extra ones come from).

Rather than mess about with this logic, which I think is correct, I have added a column to the VLAN search page which shows the active/configured ports using the VLAN. So in your example the "extra" devices would be shown having zero value in this column to indicate why they appear.

[master c282a5a5] #688 Amend vlan search to show number of ports actually using the vlan
