### ISSUE TITLE
Extended MAC-Search (with #721) not working with partial search on

### ISSUE THREAD

**Issue by pidotgit** [netdisco/netdisco#743]
Since implementation of #721 it is possible to search for MAC in different formats without specifying the exact format, but this does not work when partial search is enabled

Examples

Working examples
http://<span></span>10.11.22.33/search?tab=node&q=b4b6.862a.abcd&stamps=on&deviceports=on&daterange=&mac_format=IEEE
http://<span></span>10.11.22.33/search?tab=node&q=b4:b6:862a:<n/>ab:cd&stamps=on&deviceports=on&daterange=&mac_format=IEEE
http://<span></span>10.11.22.33/search?tab=node&q=b4b6862aabcd&stamps=on&deviceports=on&daterange=&mac_format=IEEE

If partial Search is enabled
This works:
http\://10.11.22.33/search?tab=node&q=b4:b6:86:2a:<n/>ab:cd&stamps=on&deviceports=on&partial=on&daterange=&mac_format=IEEE

not working (empty result)
http\://10.11.22.33/search?tab=node&q=b4b6.862a.abcd&stamps=on&deviceports=on&partial=on&daterange=&mac_format=IEEE
http\://10.11.22.33/search?tab=node&q=b4b6862aabcd&stamps=on&deviceports=on&partial=on&daterange=&mac_format=IEEE

is it possible to modify the search like:
if search-input is exaclty a complete MAC address (any given format) then show the client and ignore the expressed mac_format?

my 2CentLogic
If SearchString.delimit(.:- whitespace).Length = 12 and charactersAreOnly([a-f][A-F][0-9])
Then search for this MAC (+ append default search results ? if possible ? so we dont break the search if my partial search string only looks like a mac but is a partial client id), else do default search

**Comment by ollyg** [comment]
Hi @pidotgit 

In short, partial search will only ever work for IEEE format MAC addresses. This is because it uses SQL wildcards in the search query and the internal database format of the MAC is in IEEE style.

Also, just to clear up a misunderstanding, the mac_format web interface option relates to the *display* of MAC addresses in results, and does not affect the query at all.

So, I am not sure what to do... perhaps add a tooltip to the web interface to say that Partial only works on IEEE format addresses.

**Comment by ollyg** [comment]
UI tweaks in
[master 7cf2bde4] #743 make clear when partial MAC search can be used
