### ISSUE TITLE
[feature-request] display network subnet of VLAN

### ISSUE THREAD

**Issue by pidotgit** [netdisco/netdisco#756]
Hello,

i would like to request the feature to display the corresponding subnet to the VLAN of an accessport in Port-Search.

Our Clients require a DHCP reservation to access a Network. In case of a worktask to create a new IP reservation we get the Information of the Port-Description (unique) to identify the location / switch / port, but from this point on its faster to login to the switch and aquire the necessary Information via "sh ip dhcp snooping binding".

We cant use the "Connected Nodes & Devices" to identify the corresponding Network because the mapped MAC to IP information could be from a different Network (case: client moved from a different Network, MAC has been mapped to old IP).

Greetings
Piotr

**Comment by ollyg** [comment]
Hi @pidotgit can I just check - this is in the Port Search results? (so not the Device Ports detail pane)

**Comment by pidotgit** [comment]
Thats correct.
The automagic of the search realizes that the input equals to a port-description and shows in that case the Port Search result

**Comment by inphobia** [comment]
i'm not completely clear on what the issue here is.

if i enter this in the search window & use the search ports option it shows the vlan entries:

![image](https://user-images.githubusercontent.com/39005454/100387440-666a4e00-3028-11eb-9ef3-e82d45268e34.png)

![image](https://user-images.githubusercontent.com/39005454/100387485-7b46e180-3028-11eb-8a92-2b8c6c9f4561.png)


could you provide an example perhaps of what you're trying to do?

**Comment by pidotgit** [comment]
Right, a example should explain that more clearly:
![example](https://user-images.githubusercontent.com/70077636/100434665-20030680-309d-11eb-8598-c71b8681c06f.png)

My point is about the VLAN information: it would be nice if netdisco could display the corresponting network of the shown VLAN

**Comment by ollyg** [comment]
Hi, as far as I can tell, this is not possible with Netdisco. This is because:

- vlan is a layer 2 concept, does not know about IPs
- subnet (IP Prefix) is a layer 3 concept, and independent of ports

The only way to do this would be to somehow know the layer 3 virtual interfaces which exist within vlans (e.g. in Cisco speak, interface Vlan123) and then use the prefixes assigned to them to map back to Vlans. But I don't think Netdisco does this or stores the data needed to work it out (and then there would need to be assumptions about the virtual interfaces).

**Comment by ollyg** [comment]
JVI says:

> what could also help the requester is if we'd show DHCP snooping entries for each node, if known. However, that would first require extending SNMP::Info with methods to collect that info from devices that support it. Which would make it non-trivial to develope/test/implement.

**Comment by ollyg** [comment]
I've added this to the wishlist: https://github.com/netdisco/netdisco/wiki/Wishlist

Sorry we cannot address it right now.
