### ISSUE TITLE
Feature request/discussion: can we add DNS caching for reverse lookups?

### ISSUE THREAD

**Issue by rc9000** [netdisco/netdisco#779]
## Current Behavior

Netdisco is always the "top talker" on our DNS servers, doing multiple PTR lookups per second in even moderately sized networks. AnyEvent::DNS seems not to use any cache at all.

## Possible Solution

As I understand, AnyEvent::DNS bypasses the OS resolution mechanisms and caching (eg. nscd) and directly contacts the DNS server. However there are at least these two modules which seem to provide a cache plug-in:

 * https://metacpan.org/pod/AnyEvent::CacheDNS
 * https://metacpan.org/pod/AnyEvent::DNS::Cache::Simple

Would you guys be open to adding one of these, probably as an option controlled via deployment.yml? Any experience with one of these modules? 

I'm also willing to do the coding/testing part once we agree on an implementation.

**Comment by inphobia** [comment]
after having a look over the anyevent::dns code it does indeed seems to go directly to the dns servers defined on the os by design.

while i've personally haven't run into this issue, https://github.com/kazeburo/AnyEvent-DNS-Cache-Simple seems to be the better option of the 2:
 * seems easier to add
 * seems easy to be an option to enable/disable

all that being said...
i dunno if using caching (or nscd) will fix this. i'm guessing the dns load is due to node reverse ip lookups from macsuck/arpnip? the default for those is to run every hour, while the default nscd cache seems to be 600 seconds for a positive lookup and 0 seconds for a negative one. so unless netdisco is running on a server that has cached those entries for other reasons i don't think this will make a difference.

you can ofcourse change the ttl to several hours, but then you might get out of date info.

for my environment with clients switching between wired, wireless & mobile connections - and ip adresses being reused, i prefer non cached lookups. we do however only arpnip/macsuck every 4 hours. and due to the current work from home policy we only have 13.000 ip's (+-6000 active) in our db. i did check our dns servers since i'm curious and noticed arpwalk does cause a cpu spike when it runs, but only briefly and without much impact (dns == windows 2012r2 running on vmware with 4cpus).

i'm not sure what the next steps are for this. perhaps lowering `max_outstanding` can spread the load over a longer period if your dns servers are having issues. personally i prefer forced direct lookups after having run into to many dns caching problems (for various reasons), but i'm not opposed to any caching layer. i do wonder if it will have an impact.
another way to go is to have an option in netdisco to update ptr records is a seperate worker, so you can run it on a lower frequency, but that also has drawbacks of data not being in sync.

**Comment by rc9000** [comment]
Hi @inphobia

Yes I totally agree, the caching would need to be quite long to really make a difference. I meant to close this issue already but I forgot. In fact we found another script on the Netdisco server that was also generating a lot of traffic, and with it removed the number of queries is still high but got the "acceptable" stamp of approval from our DNS operators :)
