### ISSUE TITLE
Cannot see IP information from clients connected to switches in netdisco, just MAC addresses

### ISSUE THREAD

**Issue by ARK-RAVI** [netdisco/netdisco#791]
Hello,

We have an issue regarding missing IP information from clients (multiple vendors) connected to switches in our whole netdisco environment.
Unfortunately we can see just the MAC address instead of MAC address and IP address.

Examples:  Please find the attached images
![1](https://user-images.githubusercontent.com/22443554/121491443-3ee03f00-c9d6-11eb-88cf-bc5ef684af0b.jpg)
![2](https://user-images.githubusercontent.com/22443554/121491447-3f78d580-c9d6-11eb-836b-a52328d96761.jpg)
![3](https://user-images.githubusercontent.com/22443554/121491449-3f78d580-c9d6-11eb-8a95-9cfc4b3428ed.jpg)

Where could be the error located?  ARP table issue? Netdisco arpnip issue? Arpnip timeout issue?
We are using mainly Cisco Switches. We don’t see this issue on specific switches. We cannot point to an specific vendor. It happens with different vlans.
Many thanks.

**Comment by inphobia** [comment]
> We have an issue regarding missing IP information from clients (multiple vendors) connected to switches in our whole netdisco environment.
> Unfortunately we can see just the MAC address instead of MAC address and IP address.

missing ip adresses are due to missing arp tables/mappings. the most common issue is that you're not polling the default gateway for the device. second most common issue is that the default gaterway for the device either doesn't provide that info via snmp or hides it in some weird oid.

in your first example, `EM06-PRINT`, it says it's on vlan 40. are you polling whatever the gateway is for vlan 40?

there are other possible reasons why the info is missing, but lets start with checking if the routers are also polled via netdisco.

**Comment by ollyg** [comment]
closing. Please re-open if you are still stuck.
