### ISSUE TITLE
Telnet support

### ISSUE THREAD

**Issue by icovada** [netdisco/netdisco#817]
I know telnet is not best practice, however netdisco would be most useful exactly on the kind of environments where there is no standard, no documentation, and no security

Has anyone thought about implementing telnet transport support?

I would, but I don't know PERL

**Comment by rc9000** [comment]
Netdisco uses SNMP for most things so Telnet vs. SSH doesn't matter. Where exactly do you think Telnet would be needed in your case?

**Comment by ollyg** [comment]
Indeed it is possible but requires a lot of code to be written.
We have a placeholder for where Telnet support would go, so if anyone wants to find the time, great.

However if the question is "is this easily done without a lot of Perl?" then sorry, it's no.

for the benefit of future watchers, I am talking about examples here with SSH but more, as device discovery also needed:
https://github.com/netdisco/netdisco/blob/master/lib/App/Netdisco/Transport/SSH.pm
https://github.com/netdisco/netdisco/blob/master/lib/App/Netdisco/Worker/Plugin/Arpnip/Nodes.pm

**Comment by rc9000** [comment]
@ollyg as a side note I'd like to say that our organization is very grateful for [Net::Appliance::Session](https://metacpan.org/pod/Net::Appliance::Session) and especially the transparent handling of SSH and Telnet was a killer feature during a short transition period that took about a decade :) 

I totally agree with the rest, it would be quite a lot of work and it's unlikely to attract many volunteers. 

@icovada we have been using [IBM Tivoli Network Manager](https://www.ibm.com/docs/en/nsa-and-bsm?topic=monitoring-tivoli-network-manager) in the past, it can create a L1/L2/L3 topology and inventory just from Telnet access and show commands. It probably costs an arm and a leg though.

**Comment by icovada** [comment]
@rc9000 working as a consultant, most of the time the kind of customer who doesn't have any documentation, network drawings and ssh enabled also doesn't have snmp

@rc9000 I ended up writing a python library of my own, netwalk. After publishing it last week, someone it described it as "netdisco, but with less features" so I decided to check out this project, and I really wanted to use it, but it seems like it's not a good fit for me

**Comment by ollyg** [comment]
Thanks both!

I will also add, probably the most challenging part is the set of commands used to get the basic device parameters out (serial number, port names, and so on) as these are really not standardised across vendors.

We can get ARP tables using SSH because "show arp" is fairly simple and narrow job and easy to munge into the data Netdisco needs. But that still uses a lot of SNMP around it to gather the basic device parameters (and the MAC address table).

Effectively we are looking at a clone of SNMP::Info which abstracts the vendor-specific commands and gives Netdisco a stable API. For the SSH parts gathering ARP tables we are doing that: all the Perl package files under Platform:: namespace.

Sorry for the long info, just adding detail on why this is not straightforward to implement (or even to port your netwalk library into Netdisco).

**Comment by icovada** [comment]
Thank you. I edited my previous message while you were replying, I'll post it back here:

"I am not asking for the project to bend over to my needs. I am just asking if someone had considered adding telnet support. I understand adding features is hard. I would volunteer to do it myself but I have never coded in PERL and I am unable help"

So I completely understand it's going to be complex, and if my request only impacts a tiny fraction of users it makes complete sense to not implement it

**Comment by ollyg** [comment]
No worries @icovada 
What I was trying to express is that actually there is already a "hook" inside Netdisco for Telnet support because it was written at the time of implementing SSH support.

The challenge is getting the commands and mapping data returned into the Netdisco data schema so it works across platforms. It's a lot of work (especially for the first implementation).

Given all the other things people are asking for, yes there are not a lot of people asking for Telnet so not highest priority. We can add this to https://github.com/netdisco/netdisco/wiki/Wishlist :-D
