### ISSUE TITLE
Feature suggestion - DNS display in undiscovered neighbour report

### ISSUE THREAD

**Issue by kingtrw** [netdisco/netdisco#829]
The undiscovered neighbour report /admin/undiscoveredneighbors is very useful, but it only lists IP address and interface e.g.

172.x.y.z
GigabitEthernet1/0/1

If you click the IP address, it takes you to the node view where you can see the IP address and the hostname

172.x.y.z (switchname.domain)

It would be very useful (and hopefully easy) to include the hostname in the undiscovered neighbours report.

Thanks!

**Comment by ollyg** [comment]
This is, naturally, tricker than it seems. The current query does not work on the Node table at all, as it's a query on the Device Ports table. And if we relate to the Node table, there can be more than one Node with an IP address (it happens).

This is why the report is written as it is. So that the query itself is fast, and then a Node Search shows where the IP has been configured.
