### ISSUE TITLE
"Port Free" Calculation

### ISSUE THREAD

**Issue by cesacal** [netdisco/netdisco#863]
I would like to know how Netdisco makes the calculation of the "Port Free" data.
We have a switch that has been reloaded 6 days ago, and in the port section we see "Last Change" updated to the day of the switch reload.

However, we have the "port free" date set to 3 months, and it still shows ports free (see image attached).
How does netdisco do this "port free" calculation? Does netdisco saves any other data on the data base different to "last change"?

It would be very useful for me to understand this point.
Thanks for your help.

![Port Free Calculation](https://user-images.githubusercontent.com/97600299/160546882-262e8435-8f82-4438-8af0-411e648208bb.jpg)

**Comment by rc9000** [comment]
Netdisco uses the mac:port mappings that are stored in the database to determine this. Roughly: if the port is down, it looks at the last known mac on the port, and if it was seen last before the "free if down for" timerange, the port is considered free.

You can see all the involved code and queries if you search for `is_free` and `last_node` in this repo.

The SNMP "last change" on the interface can not be used for this, since as you notice it resets if the device reboots, and it can also be zero if the snmp agent is restarted after the initial boot. 

Cheers & HTH
Christian

**Comment by cesacal** [comment]
@rc9000 I´ve been looking for the "free port" calculation, and even though it´s a complex query with many tables involved, I think it´s much clearer than before for me.

Thanks a lot for you help.

**Comment by cesacal** [comment]
@rc9000 Hello Christian, I´ve been looking through the code section, finding the part of code where "is_free" and "last_node" are calculated.

I would like to ask you one more question: would it be possible to add"last_node.time_last" on the report of port?
Or even a column of "days without use", making the difference between (TODAY - last_node.time_last)

Thanks a lot!

**Comment by cesacal** [comment]
Hi again @rc9000 , 

I would like to ask you one more question: would it be possible to add "last_node.time_last" on the report of port?
Or even a column of "days without use", making the difference between (TODAY - last_node.time_last)

**Comment by ollyg** [comment]
Hi @cesacal it is already there -- if you select both "Archived Data" and "Age Stamp" options under "Node Properties" in the sidebar. Then you will see the last node, and the time since it was seen. For example:

`aa:bb:cc:xx:xx:xx (2 years 3 months 10 days 05:26:00)`
