### ISSUE TITLE
ajax/device/ports_csv.tt header mismatch

### ISSUE THREAD

**Issue by inphobia** [netdisco/netdisco#932]
almost exactly like #930 but then for the csv export
need to reallign the headers and rows to match up again.

which should be hard, until i noticed something that bugged me:
while ports.tt puts a "/" between configured and running duplex, ports_csv.tt speratates them with a ",".

the reason for this seems to be that:

ports.tt puts duplex and duplex_admin from the device_port table in the "duplex" column
ports_csv.tt however has "duplex setting" & "duplex" as seperate headers and as such seperate columns for this

imo this should not differ, so either we:
 * add a "duplex configured" column to ports.tt
 * or do the reverse: merge duplex & duplex admin in ports_csv.tt

i feel like adding duplex configured to ports.tt is the oorrect path, but the ports overview is alrdy crowded as it is.

any thoughts about which way we should go?

**Comment by ollyg** [comment]
well, this might be a #wontfix because it's not just duplex where the single web column expands into multiple csv columns. you can see this at the start of the template:
https://github.com/netdisco/netdisco/blob/master/share/views/ajax/device/ports_csv.tt#L9

Nodes, neighbors, power, they all expand to more. And the REST API is just the same (inconsistent with the others) because it just dumps the database columns/fields for the device or node.

I think the reasoning is that if you're getting csv you're then doing some kind of data post-processing which could recreate the web version of the field if you want, but it would be tricky to go the other way from a combined field.
