### ISSUE TITLE
device ports - duplex & speed - running vs configured

### ISSUE THREAD

**Issue by inphobia** [netdisco/netdisco#933]
when looking into #930 , opening #932 and netdisco/snmp-info#473 i ended up with this:

the device_port table has columns for:
 * speed
 * speed_admin
 * duplex
 * duplex_admin

all of them either contain whatever snmp::info found, or they can be null. but then their usage starts to diverge

 1. ports.tt has a culumn for speed admin, but not for duplex admin
   - i don't see why this is, so i propose
     - add a new column to ports.tt for duplex admin
     - remove speed admin & display it in the same fashion as duplex
 2. stop lying about duplex admin
   - if duplex admin is null, don't lie and say it's "auto":
     - https://github.com/netdisco/netdisco/blob/84309192ef2a0fa3219cb4b0fdedf91d7c530d14/share/views/ajax/device/ports.tt#L181
   - if duplex admin was a seperate column we could leave it blank
   - or perhaps it's better to do the same and assume it's "auto" when speed admin is null
   - my preference would be adding the duplex admin column & allowing null values
 3. when the above 2 items are addressed also add the solution to ports_csv.tt

**Comment by ollyg** [comment]
You are right, a "null" in the database field is _not_ the same as an "auto" setting on the device, because it might also mean that we're unable to get the data from the device. So in the web interface if we have "null" in the database it should just be blank.

Might want to check on the MIB-II definitions of these fields, though, to see whether there is some strange default and what the range of enumerated options is. I'm not at a computer right now to see (could use the MIB browser in Netdisco for it as the MIB definitions and enumeration options are shown!).

**Comment by ollyg** [comment]
implemented in 4e6f143d
