### ISSUE TITLE
Timestamp On Discover issue

### ISSUE THREAD

**Issue by ubzmrh** [netdisco/netdisco#949]
## Expected Behavior
The column device.last_discover should be stored in UTC to permit time manipulation

## Current Behavior
The column last_discover is stored in local time

## Possible Solution
I let you decide

## Steps to Reproduce (for bugs)
1. click on  discover on device panel
2. query the device table with `select last_discover, to_timestamp(extract(epoch from last_discover)) from device `
3. compare the two values

## Context
I was curious about issue #946 and some problems with the age of free ports.
I did some tests especially around the interval between device.last_discover and the postgreSQL function now()

device.last_discover is stored as timestamp without time zone, so to compute the interval the formula is 
`age(now(), to_timestamp(extract(epoch from device.last_discover))) `
BUT  device.last_discover is stored in local time, not in UTC, and when converted in timestamp with time zone some hours are added.
(Only one for me as I'm living in France, timezone is UTC+1) 
The computed timestamp is erroneous
I made a 'discover' on a device today (2022-12-13) at 12:26 local time
after that, I do this query 
`select now(), last_discover, to_timestamp(extract(epoch from last_discover)), age(now(), to_timestamp(extract(epoch from last_discover))) from device`
> column now()                contains `2022-12-13 12:26:40.448845+01`
> column last_discover     contains `2022-12-13 12:26:20.770007` 
> column  to_timestamp  contains `2022-12-13 13:26:20.770007+01`  a value in the future !
> column age                   contains `-00:59:40.321162`  a negative value !

## Your Environment
Software	        Version
App::Netdisco	2.47.5
SNMP::Info	3.71
DB Schema	64
PostgreSQL	12.00.11
Perl	                5.16.3

**Comment by ollyg** [comment]
Thanks for the report @ubzmrh 

To give some background: Netdisco 1.x had a schema with no time zone information and at the time of writing Netdisco 2.x we decided not to mess with that. Since then, we also see installations with four components of Netdisco in different time zones: the device itself, the poller code, the database server, and the user's web browser. So, I have been wary of touching any of that code because it could just mess things up for another installation with a different setup.

Personally, for example, I run all our systems in UTC ... the devices, the database, and the poller server. Then we never see issues and it works for users wherever they are in the world and wherever the network is.

Back to your issue: It is true that now() includes a time zone, so perhaps we want LOCALTIME or LOCALTIMESTAMP instead. I will have a look into it.

**Comment by ollyg** [comment]
`g grep -E 'epoch|to_timestamp|extract| age\(' lib`

**Comment by ollyg** [comment]
Thanks @ubzmrh I have made some significant updates to Netdisco which at least means it's consistently not using time zones any more, and I hope your test will verify that the situation is improved.

Ideally I would like to have time zone handling in Netdisco, but that is an even bigger job! For now, we continue to advise all users to run all Netdisco components in UTC (and even for a single server it helps, as this avoids daylight savings time changes confusion).

Thanks again.
